# Generated by Django 3.2.7 on 2021-09-06 03:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0002_osmhighway"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsmAdminBoundary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="osmhighway",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
