# Generated by Django 3.1.13 on 2021-09-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0006_auto_20210908_0214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookairoad",
            name="way_fbid",
            field=models.BigIntegerField(),
        ),
    ]
