# Generated by Django 4.0 on 2022-01-12 07:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("djangostreetmap", "0001_initial"),
        ("djangostreetmap", "0002_osmhighway"),
        ("djangostreetmap", "0003_auto_20210906_0359"),
        ("djangostreetmap", "0004_osmislands"),
        ("djangostreetmap", "0005_osmislandsareas"),
        ("djangostreetmap", "0006_auto_20211025_2148"),
        ("djangostreetmap", "0007_facebookairoad_osmhighway_bridge_osmhighway_junction_and_more"),
        ("djangostreetmap", "0008_overpassquery_remove_osmhighway_bridge_and_more"),
        ("djangostreetmap", "0009_delete_planetosmline_delete_planetosmpoint_and_more"),
        ("djangostreetmap", "0010_overpassquery_osm_id"),
        ("djangostreetmap", "0011_remove_overpassquery_osm_id_overpassresult_osm_id"),
        ("djangostreetmap", "0012_alter_overpassquery_name"),
        ("djangostreetmap", "0013_osmboundary"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OsmAdminBoundary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OsmHighway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("name", models.TextField(blank=True, null=True)),
                ("highway", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OsmIslands",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OsmIslandsAreas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("geom", django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacebookAiRoad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("way_fbid", models.BigIntegerField()),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("highway", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OverpassQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                ("date_fetched", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="", max_length=256)),
                ("response", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="OverpassResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tags", models.JSONField(null=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=3857)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("query", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="djangostreetmap.overpassquery")),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OsmBoundary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tags", models.JSONField(null=True)),
                ("meta", models.JSONField(null=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=3857)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
