# Generated by Django 4.0 on 2022-01-14 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangostreetmap', '0003_osmnode_osmrelation_osmway_osmrelationmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmrelationmember',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osmrelationmember',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangostreetmap.osmnode'),
        ),
        migrations.AlterField(
            model_name='osmrelationmember',
            name='way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangostreetmap.osmway'),
        ),
    ]
