# Generated by Django 4.0 on 2022-01-14 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0004_osmrelationmember_role_alter_osmrelationmember_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="osmrelationmember",
            name="relation",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="djangostreetmap.osmrelation"),
        ),
    ]
