# Generated by Django 4.0 on 2022-01-05 03:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0006_auto_20211025_2148"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookAiRoad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("way_fbid", models.BigIntegerField()),
                ("geom", django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ("highway", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="osmhighway",
            name="bridge",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="osmhighway",
            name="junction",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="osmhighway",
            name="oneway",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="osmhighway",
            name="highway",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="osmhighway",
            name="name",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
