# Generated by Django 4.0 on 2022-01-06 04:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0007_facebookairoad_osmhighway_bridge_osmhighway_junction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverpassQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                ("date_fetched", models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="osmhighway",
            name="bridge",
        ),
        migrations.RemoveField(
            model_name="osmhighway",
            name="junction",
        ),
        migrations.RemoveField(
            model_name="osmhighway",
            name="oneway",
        ),
        migrations.AlterField(
            model_name="osmhighway",
            name="highway",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="osmhighway",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OverpassResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tags", models.JSONField(null=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=3857)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("query", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="djangostreetmap.overpassquery")),
            ],
        ),
    ]
