# Generated by Django 4.0 on 2022-01-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0007_alter_osmnode_lat_alter_osmnode_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsmXmlImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.TextField()),
            ],
        ),
        migrations.RunSQL(
            """
            ALTER TABLE djangostreetmap_osmxmlimport alter "data" type xml using data::xml;
            """,
            None,
        ),
    ]
