# Generated by Django 4.0 on 2022-01-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0008_overpassquery_remove_osmhighway_bridge_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlanetOsmLine",
        ),
        migrations.DeleteModel(
            name="PlanetOsmPoint",
        ),
        migrations.DeleteModel(
            name="PlanetOsmPolygon",
        ),
        migrations.AddField(
            model_name="overpassquery",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="overpassquery",
            name="response",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="overpassquery",
            name="date_fetched",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
