# Generated by Django 4.0 on 2022-01-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0009_delete_planetosmline_delete_planetosmpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overpassquery",
            name="osm_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
