# Generated by Django 4.0 on 2022-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0010_overpassquery_osm_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overpassquery",
            name="osm_id",
        ),
        migrations.AddField(
            model_name="overpassresult",
            name="osm_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
