# Generated by Django 4.0 on 2022-01-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0011_remove_overpassquery_osm_id_overpassresult_osm_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overpassquery",
            name="name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
