# Generated by Django 4.0 on 2022-01-12 03:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangostreetmap", "0012_alter_overpassquery_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsmBoundary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tags", models.JSONField(null=True)),
                ("meta", models.JSONField(null=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=3857)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
