name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Test mypy
      run: |
        poetry run mypy .
    - name: Test with pytest
      run: |
        poetry run black --check .
        
    services:
        postgres:
            image: postgis/postgis:14-3.2
            # Provide the password for postgres. Should be sync'ed with test settings file.
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: post1234
                POSTGRES_DBNAME: postgres
            # Set health checks to wait until postgres has started
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 49156:5432
