name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install OS level dependencies
      run: |
        sudo apt-get update
        sudo apt-get install binutils libproj-dev gdal-bin python3-psycopg2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Lint with flake8

      if: always()
      run: |
        poetry run flake8 .
    - name: Test with pytest
      if: always()
      run: poetry run pytest --cov

    - name: Produce coverage XML
      run: poetry run coverage xml

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true

    - name: Test mypy
      if: always()
      run:  poetry run mypy .

    - name: Test with pytest
      if: always()
      run: poetry run black --check .

    services:
        postgres:
            image: postgis/postgis:14-3.2
            # Provide the password for postgres. Should be sync'ed with test settings file.
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: post1234
                POSTGRES_DBNAME: postgres
            # Set health checks to wait until postgres has started
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 49156:5432
